language: swift
osx_image: xcode9.2
xcode_project: THScrollViewMinimap.xcodeproj
xcode_scheme: THScrollViewMinimap
xcode_sdk: iphonesimulator11.2
sudo: required

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - brew update

script:
  - xcodebuild test -project THScrollViewMinimap.xcodeproj -scheme THScrollViewMinimap -configuration Debug -destination "OS=11.2,name=iPhone 8" -sdk iphonesimulator -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'THScrollViewMinimap' -X xcodeplist
